[build]
  command = "npm install"
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# API路由重定向到Netlify Functions
[[redirects]]
  from = "/api/reports"
  to = "/.netlify/functions/reports"
  status = 200

[[redirects]]
  from = "/api/report/*"
  to = "/.netlify/functions/report"
  status = 200

[[redirects]]
  from = "/api/status"
  to = "/.netlify/functions/status"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

# SPA路由支持
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "."
